### 0.データのフィルタリング・クリーニング

#### 01.データ読み込みと結合

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# データ読み込み
df1 = pd.read_csv('../data/raw/trajectories-0400-0415.csv')
df2 = pd.read_csv('../data/raw/trajectories-0500-0515.csv')
df3 = pd.read_csv('../data/raw/trajectories-0515-0530.csv')

# 結合
df = pd.concat([df1, df2, df3], ignore_index=True)

# データの確認
print(df.shape)
df.head()

(3145725, 18)

,Vehicle_ID,Frame_ID,Total_Frames,Global_Time,Local_X,Local_Y,Global_X,Global_Y,v_Length,v_Width,v_Class,v_Vel,v_Acc,Lane_ID,Preceding,Following,Space_Headway,Time_Headway
0,1,12,884,1113433136100,16.884,48.213,6042842.116,2133117.662,14.3,6.4,2,12.5,0.0,2,0,0,0.0,0.0
1,1,13,884,1113433136200,16.938,49.463,6042842.012,2133118.909,14.3,6.4,2,12.5,0.0,2,0,0,0.0,0.0
2,1,14,884,1113433136300,16.991,50.712,6042841.908,2133120.155,14.3,6.4,2,12.5,0.0,2,0,0,0.0,0.0
3,1,15,884,1113433136400,17.045,51.963,6042841.805,2133121.402,14.3,6.4,2,12.5,0.0,2,0,0,0.0,0.0
4,1,16,884,1113433136500,17.098,53.213,6042841.701,2133122.649,14.3,6.4,2,12.5,0.0,2,0,0,0.0,0.0

In [9]:
# 列名の確認
print(df.columns.tolist())

# データ型の確認
print(df.dtypes)

#欠損値　なさそう
print("\n欠損値:")
df.isnull().sum()

# 基本統計量
df.describe()

#v,accはfeet表示であることに注意

['Vehicle_ID', 'Frame_ID', 'Total_Frames', 'Global_Time', 'Local_X', 'Local_Y', 'Global_X', 'Global_Y', 'v_Length', 'v_Width', 'v_Class', 'v_Vel', 'v_Acc', 'Lane_ID', 'Preceding', 'Following', 'Space_Headway', 'Time_Headway']
Vehicle_ID         int64
Frame_ID           int64
Total_Frames       int64
Global_Time        int64
Local_X          float64
Local_Y          float64
Global_X         float64
Global_Y         float64
v_Length         float64
v_Width          float64
v_Class            int64
v_Vel            float64
v_Acc            float64
Lane_ID            int64
Preceding          int64
Following          int64
Space_Headway    float64
Time_Headway     float64
dtype: object

欠損値:

,Vehicle_ID,Frame_ID,Total_Frames,Global_Time,Local_X,Local_Y,Global_X,Global_Y,v_Length,v_Width,v_Class,v_Vel,v_Acc,Lane_ID,Preceding,Following,Space_Headway,Time_Headway
count,3.145725e+06,3.145725e+06,3.145725e+06,3.145725e+06,3.145725e+06,3.145725e+06,3.145725e+06,3.145725e+06,3.145725e+06,3.145725e+06,3.145725e+06,3.145725e+06,3.145725e+06,3.145725e+06,3.145725e+06,3.145725e+06,3.145725e+06,3.145725e+06
mean,1.218703e+03,4.179937e+03,8.351025e+02,1.113436e+12,3.950091e+01,8.605660e+02,6.042758e+06,2.133926e+06,1.613524e+01,6.833817e+00,2.035639e+00,2.167159e+01,-1.731954e-03,3.804229e+00,1.170625e+03,1.193760e+03,5.767649e+01,2.710519e+02
std,6.583922e+02,2.050875e+03,3.158688e+02,1.912281e+06,2.098778e+01,4.479828e+02,6.745329e+01,4.439525e+02,7.194716e+00,8.983861e-01,2.015449e-01,1.294448e+01,4.886494e+00,1.675106e+00,7.073482e+02,7.068590e+02,3.972120e+01,1.612196e+03
min,1.000000e+00,4.000000e+00,2.030000e+02,1.113433e+12,0.000000e+00,0.000000e+00,6.042590e+06,2.133048e+06,5.400000e+00,3.100000e+00,1.000000e+00,0.000000e+00,-1.120000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,6.990000e+02,2.441000e+03,6.390000e+02,1.113434e+12,1.879400e+01,4.844290e+02,6.042702e+06,2.133554e+06,1.380000e+01,6.300000e+00,2.000000e+00,1.275000e+01,-8.900000e-01,2.000000e+00,6.170000e+02,6.420000e+02,3.535000e+01,1.950000e+00
50%,1.246000e+03,4.182000e+03,7.900000e+02,1.113437e+12,4.099300e+01,8.479820e+02,6.042762e+06,2.133914e+06,1.480000e+01,6.900000e+00,2.000000e+00,2.008000e+01,0.000000e+00,4.000000e+00,1.201000e+03,1.224000e+03,4.955000e+01,2.720000e+00
75%,1.680000e+03,5.911000e+03,9.690000e+02,1.113438e+12,5.468200e+01,1.247190e+03,6.042815e+06,2.134310e+06,1.590000e+01,7.400000e+00,2.000000e+00,2.870000e+01,9.100000e-01,5.000000e+00,1.665000e+03,1.682000e+03,7.088000e+01,3.970000e+00
max,2.911000e+03,8.741000e+03,1.935000e+03,1.113438e+12,9.699600e+01,1.790771e+03,6.042905e+06,2.134845e+06,7.770000e+01,8.500000e+00,3.000000e+00,9.530000e+01,1.120000e+01,7.000000e+00,3.366000e+03,3.366000e+03,1.321550e+03,1.173390e+04

In [3]:
# 車種の分布確認
print("車種の分布:")
print(df['v_Class'].value_counts())

# 車線の分布確認
print("\n車線の分布:")
print(df['Lane_ID'].value_counts().sort_index())

# 速度・加速度の基本統計
print("\n速度(feet/s):")
print(df['v_Vel'].describe())

print("\n加速度(feet/s²):")
print(df['v_Acc'].describe())

車種の分布:
v_Class
2    3013949
3     121944
1       9832
Name: count, dtype: int64

車線の分布:
Lane_ID
1    284021
2    579912
3    506923
4    606013
5    531467
6    540666
7     96723
Name: count, dtype: int64

速度(feet/s):
count    3.145725e+06
mean     2.167159e+01
std      1.294448e+01
min      0.000000e+00
25%      1.275000e+01
50%      2.008000e+01
75%      2.870000e+01
max      9.530000e+01
Name: v_Vel, dtype: float64

加速度(feet/s²):
count    3.145725e+06
mean    -1.731954e-03
std      4.886494e+00
min     -1.120000e+01
25%     -8.900000e-01
50%      0.000000e+00
75%      9.100000e-01
max      1.120000e+01
Name: v_Acc, dtype: float64

#### 02.車線と車種のフィルタリング

In [13]:
# ① 車線フィルタ（Lane 2,3,4のみ）
df_lane = df[df['Lane_ID'].isin([2, 3, 4])]

# ② 車種フィルタ（バイク除外）
df_filtered = df_lane[df_lane['v_Class'].isin([2, 3])]

print(f"元のデータ: {len(df):,}行")
print(f"フィルタ後: {len(df_filtered):,}行")

# 車線の分布確認
print("\n車線の分布:")
print(df_filtered['Lane_ID'].value_counts().sort_index())

# 車種の分布確認
print("車種の分布:")
print(df_filtered['v_Class'].value_counts())

元のデータ: 3,145,725行
フィルタ後: 1,691,818行

車線の分布:
Lane_ID
2    579432
3    506707
4    605679
Name: count, dtype: int64
車種の分布:
v_Class
2    1608495
3      83323
Name: count, dtype: int64