# どのデータを使うべきかを確認する

## ３つの時間ごとのtrajectry_data

In [22]:
import pandas as pd
from pathlib import Path

path_1 = Path('../data/raw/trajectories-0400-0415.txt')
path_2 = Path('../data/raw/trajectories-0500-0515.txt')
path_3 = Path('../data/raw/trajectories-0515-0530.txt')

columns = [
    'Vehicle_ID', 'Frame_ID', 'Total_Frames', 'Global_Time', 'Local_X', 'Local_Y',
    'Global_X', 'Global_Y', 'v_Length', 'v_Width', 'v_Class', 'v_Vel', 'v_Acc',
    'Lane_ID', 'Preceding', 'Following', 'Space_Headway', 'Time_Headway'
]

df_1 = pd.read_csv(path_1, sep=r'\s+', header=None, names=columns)
df_2 = pd.read_csv(path_2, sep=r'\s+', header=None, names=columns)
df_3 = pd.read_csv(path_3, sep=r'\s+', header=None, names=columns)

In [23]:
print(df_1.shape)
print('df rows:', len(df_1))
df_1.head()

(1262678, 18)
df rows: 1262678

,Vehicle_ID,Frame_ID,Total_Frames,Global_Time,Local_X,Local_Y,Global_X,Global_Y,v_Length,v_Width,v_Class,v_Vel,v_Acc,Lane_ID,Preceding,Following,Space_Headway,Time_Headway
0,1,12,884,1113433136100,16.884,48.213,6042842.116,2133117.662,14.3,6.4,2,12.5,0.0,2,0,0,0.0,0.0
1,1,13,884,1113433136200,16.938,49.463,6042842.012,2133118.909,14.3,6.4,2,12.5,0.0,2,0,0,0.0,0.0
2,1,14,884,1113433136300,16.991,50.712,6042841.908,2133120.155,14.3,6.4,2,12.5,0.0,2,0,0,0.0,0.0
3,1,15,884,1113433136400,17.045,51.963,6042841.805,2133121.402,14.3,6.4,2,12.5,0.0,2,0,0,0.0,0.0
4,1,16,884,1113433136500,17.098,53.213,6042841.701,2133122.649,14.3,6.4,2,12.5,0.0,2,0,0,0.0,0.0

In [24]:
print(df_2.shape)
print('df rows:', len(df_2))
df_2.head()

(1549918, 18)
df rows: 1549918

,Vehicle_ID,Frame_ID,Total_Frames,Global_Time,Local_X,Local_Y,Global_X,Global_Y,v_Length,v_Width,v_Class,v_Vel,v_Acc,Lane_ID,Preceding,Following,Space_Headway,Time_Headway
0,284,63,526,1113436773200,41.375,66.469,6042864.125,2133138.844,15.4,5.9,2,44.55,0.00,4,0,0,0.0,0.0
1,284,64,526,1113436773300,41.375,71.069,6042863.571,2133143.309,15.4,5.9,2,44.55,0.00,4,0,0,0.0,0.0
2,284,65,526,1113436773400,41.374,75.570,6042863.016,2133147.775,15.4,5.9,2,44.55,0.00,4,0,0,0.0,0.0
3,284,66,526,1113436773500,41.373,80.070,6042862.462,2133152.241,15.4,5.9,2,44.55,0.00,4,0,0,0.0,0.0
4,284,67,526,1113436773600,41.372,84.607,6042861.904,2133156.736,15.4,5.9,2,44.55,-6.14,4,0,0,0.0,0.0

In [25]:
print(df_3.shape)
print('df rows:', len(df_3))
df_3.head()

(1753791, 18)
df rows: 1753791

,Vehicle_ID,Frame_ID,Total_Frames,Global_Time,Local_X,Local_Y,Global_X,Global_Y,v_Length,v_Width,v_Class,v_Vel,v_Acc,Lane_ID,Preceding,Following,Space_Headway,Time_Headway
0,3,613,1153,1113437626200,28.369,63.998,6042851.531,2133134.762,12.8,6.8,2,8.86,0.00,3,9,0,21.17,2.39
1,3,614,1153,1113437626300,28.370,64.498,6042851.469,2133135.258,12.8,6.8,2,8.86,0.00,3,9,0,21.59,2.44
2,3,615,1153,1113437626400,28.372,65.497,6042851.346,2133136.250,12.8,6.8,2,8.86,0.00,3,9,0,21.51,2.43
3,3,616,1153,1113437626500,28.374,66.498,6042851.223,2133137.243,12.8,6.8,2,8.86,0.00,3,9,0,21.42,2.42
4,3,617,1153,1113437626600,28.375,67.256,6042851.143,2133137.889,12.8,6.8,2,8.86,1.15,3,9,0,21.58,2.44

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 時間帯の識別列を追加 (id の重複があるため)
df_1['time_period'] = 1  # 4:00-4:15
df_2['time_period'] = 2  # 5:00-5:15
df_3['time_period'] = 3  # 5:15-5:30

# 結合
df = pd.concat([df_1, df_2, df_3], ignore_index=True)

# データの確認
print(df.shape)
df.head()

(4566387, 19)

,Vehicle_ID,Frame_ID,Total_Frames,Global_Time,Local_X,Local_Y,Global_X,Global_Y,v_Length,v_Width,v_Class,v_Vel,v_Acc,Lane_ID,Preceding,Following,Space_Headway,Time_Headway,time_period
0,1,12,884,1113433136100,16.884,48.213,6042842.116,2133117.662,14.3,6.4,2,12.5,0.0,2,0,0,0.0,0.0,1
1,1,13,884,1113433136200,16.938,49.463,6042842.012,2133118.909,14.3,6.4,2,12.5,0.0,2,0,0,0.0,0.0,1
2,1,14,884,1113433136300,16.991,50.712,6042841.908,2133120.155,14.3,6.4,2,12.5,0.0,2,0,0,0.0,0.0,1
3,1,15,884,1113433136400,17.045,51.963,6042841.805,2133121.402,14.3,6.4,2,12.5,0.0,2,0,0,0.0,0.0,1
4,1,16,884,1113433136500,17.098,53.213,6042841.701,2133122.649,14.3,6.4,2,12.5,0.0,2,0,0,0.0,0.0,1

In [27]:
# 行数の確認
print('df1 rows:', len(df_1))
print('df2 rows:', len(df_2))
print('df3 rows:', len(df_3))
print('combined rows:', len(df))

df1 rows: 1262678
df2 rows: 1549918
df3 rows: 1753791
combined rows: 4566387

## 直接dataタブからダウンロードしたデータ

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# データ読み込み
df = pd.read_csv('../data/raw/Next_Generation_Simulation_(NGSIM)_Vehicle_Trajectories_and_Supporting_Data_20260707.csv')

# データの確認
print(df.shape)
df.head()

C:\Users\AMhetero\AppData\Local\Temp\ipykernel_20624\2684728867.py:6: DtypeWarning: Columns (0: Local_Y, 1: Space_Headway) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/raw/Next_Generation_Simulation_(NGSIM)_Vehicle_Trajectories_and_Supporting_Data_20260707.csv')

(4566387, 25)

,Vehicle_ID,Frame_ID,Total_Frames,Global_Time,Local_X,Local_Y,Global_X,Global_Y,v_length,v_Width,...,D_Zone,Int_ID,Section_ID,Direction,Movement,Preceding,Following,Space_Headway,Time_Headway,Location
0,2071,8323,379,1113438397200,7.224,0.0,6042842.456,2133039.613,12.3,6.8,...,NaN,NaN,NaN,NaN,NaN,"2,060",0,146.57,"9,999.99",i-80
1,2071,8324,379,1113438397300,7.239,0.0,6042842.112,2133042.392,12.3,6.8,...,NaN,NaN,NaN,NaN,NaN,"2,060",0,150.25,"9,999.99",i-80
2,1895,6565,"1,958",1113438221400,42.224,0.0,6042877.191,2133043.912,14.8,6.9,...,NaN,NaN,NaN,NaN,NaN,"1,887",0,40.08,"9,999.99",i-80
3,1895,6566,"1,958",1113438221500,42.227,0.0,6042877.124,2133044.458,14.8,6.9,...,NaN,NaN,NaN,NaN,NaN,"1,887",0,41.1,"9,999.99",i-80
4,1895,6567,"1,958",1113438221600,42.230,0.0,6042877.056,2133045.004,14.8,6.9,...,NaN,NaN,NaN,NaN,NaN,"1,887",0,42.16,"9,999.99",i-80

In [4]:
print('combined rows:', len(df))

combined rows: 4566387